# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpb/server.proto\x12\x03ota\"F\n\x0bVersionInfo\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x11\n\tfile_name\x18\x03 \x01(\t\";\n\x13\x44ownloadFileRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x11\n\tfile_name\x18\x02 \x01(\t\"\'\n\x14\x44ownloadFileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32S\n\nFileServer\x12\x45\n\x0c\x44ownLoadFile\x12\x18.ota.DownloadFileRequest\x1a\x19.ota.DownloadFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONINFO']._serialized_start=24
  _globals['_VERSIONINFO']._serialized_end=94
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=96
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=155
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=157
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=196
  _globals['_FILESERVER']._serialized_start=198
  _globals['_FILESERVER']._serialized_end=281
# @@protoc_insertion_point(module_scope)
